### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by PXke** [codeivate/codeivate-jetbrains#1]
Could we have please, the source code, to for example try to port it for Eclipse ?

**Comment by p4ul** [comment]
@PXke sorry still thinking about this.

**Comment by PXke** [comment]
No problem, take your time, perhaps there is alternative possibilities, like, let say an API to post stat informations and the specification that a plugin should respect, or else :smile:

**Comment by dhyegocalota** [comment]
:+1: +1
